#!/usr/bin/env bash
source "$HOME/.dotfiles/Helpers/colors.sh"

if [[ ! -f ~/.dotfiles/Builds/copy_context ]]; then
	echo "test"
	if ! command -v cc &>/dev/null; then
		error "cc is not installed. Please install it."
		exit 1
	fi

	cc -O3 -march=native -o ~/.dotfiles/Builds/copy_context ~/.dotfiles/Helpers/copy_context.c
fi

if command -v pbcopy &>/dev/null; then
	~/.dotfiles/Builds/copy_context | pbcopy
	success "All text files copied to clipboard."
	exit 0
fi

if command -v xclip &>/dev/null; then
    ~/.dotfiles/Builds/copy_context | xclip -selection clipboard
	success "All text files copied to clipboard."
	exit 0
fi

error "xclip or pbcopy is not installed. Please install it."
exit 1