#!/usr/bin/env bash
source "$HOME/.dotfiles/Helpers/colors.sh"

warning "Are you sure you want to reset all changes? (y/n)"
read response
if [[ "$response" != "y" || "$response" != "Y" ]]; then

	info "Changes have not been reset."
	exit 0
fi
git reset --hard
success "Changes have been reset."
