#include <clang/AST/AST.h>
#include <clang/AST/RecursiveASTVisitor.h>
#include <clang/Frontend/FrontendActions.h>
#include <clang/Tooling/Tooling.h>
#include <clang/Rewrite/Core/Rewriter.h>
#include <clang/Lex/Lexer.h>
#include <clang/Frontend/CompilerInstance.h>

#include <iostream>
#include <string>
#include <vector>
#include <iterator>

using namespace clang;
using namespace clang::tooling;

class FixerVisitor : public RecursiveASTVisitor<FixerVisitor>
{
public:
    explicit FixerVisitor(Rewriter &R) : R(R) {}

    bool VisitReturnStmt(ReturnStmt *stmt)
    {
        Expr *expr = stmt->getRetValue();
        if (!expr)
            return true;

        // Peel back compiler-inserted invisible nodes (like copy constructors
        // and temporaries) to see if the outermost user-written expression is a ParenExpr.
        Expr *E = expr;
        while (E) {
            Expr *Next = E->IgnoreImplicit();

            if (auto *EWC = dyn_cast<ExprWithCleanups>(Next)) {
                Next = EWC->getSubExpr();
            } else if (auto *CE = dyn_cast<CXXConstructExpr>(Next)) {
                // If the constructor is implicitly generated by the compiler
                // (NOT a CXXTemporaryObjectExpr like `std::string("test")` explicitly written by the user)
                if (!isa<CXXTemporaryObjectExpr>(CE) && CE->getNumArgs() > 0)
                    Next = CE->getArg(0);
                else
                    break;
            } else if (auto *BTE = dyn_cast<CXXBindTemporaryExpr>(Next)) {
                Next = BTE->getSubExpr();
            } else if (auto *MTE = dyn_cast<MaterializeTemporaryExpr>(Next)) {
                Next = MTE->getSubExpr();
            }

            // If we didn't dig any deeper, stop looping
            if (Next == E)
                break;
            E = Next;
        }

        // If the user already wrapped the expression in parentheses, do nothing!
        if (E && isa<ParenExpr>(E))
            return true;

        SourceLocation start = expr->getBeginLoc();
        SourceLocation end = expr->getEndLoc();

        if (start.isInvalid() || end.isInvalid() || start.isMacroID() || end.isMacroID())
            return true;

        SourceManager &SM = R.getSourceMgr();

        R.InsertText(start, "(", true, true);
        SourceLocation endLoc = Lexer::getLocForEndOfToken(end, 0, SM, R.getLangOpts());
        if (endLoc.isValid()) {
            R.InsertText(endLoc, ")", true, true);
        }

        return true;
    }

    bool VisitFunctionDecl(FunctionDecl *func)
    {
    if (func->isImplicit())
        return true;

    // If it already has parameters (e.g. `int a`), do nothing
    if (func->getNumParams() != 0)
        return true;

    TypeSourceInfo *tsi = func->getTypeSourceInfo();
    if (!tsi)
        return true;

    TypeLoc tl = tsi->getTypeLoc().IgnoreParens();
    FunctionTypeLoc ftl = tl.getAs<FunctionTypeLoc>();
    if (!ftl)
        return true;

    SourceLocation lParen = ftl.getLParenLoc();
    SourceLocation rParen = ftl.getRParenLoc();

    if (lParen.isInvalid() || rParen.isInvalid() || lParen.isMacroID() || rParen.isMacroID())
        return true;

    R.ReplaceText(SourceRange(lParen, rParen), "(void)");

    return true;
    }

private:
    Rewriter &R;
};

class FixerConsumer : public ASTConsumer
{
public:
    explicit FixerConsumer(Rewriter &R) : V(R) {}

    void HandleTranslationUnit(ASTContext &Ctx) override
    {
        V.TraverseDecl(Ctx.getTranslationUnitDecl());
    }

private:
    FixerVisitor V;
};

class FixerAction : public ASTFrontendAction
{
public:
    void EndSourceFileAction() override
    {
        SourceManager &SM = R.getSourceMgr();
        FileID mainFileID = SM.getMainFileID();

        // If the rewriter made changes, print the rewritten code
        if (auto *rewriteBuf = R.getRewriteBufferFor(mainFileID)) {
            rewriteBuf->write(llvm::outs());
        } else {
            // If NO changes were made, print the original unmodified code
            llvm::outs() << SM.getBufferData(mainFileID);
        }
    }

    std::unique_ptr<ASTConsumer> CreateASTConsumer(
        CompilerInstance &CI, StringRef) override
    {
        R.setSourceMgr(CI.getSourceManager(), CI.getLangOpts());
        return std::make_unique<FixerConsumer>(R);
    }

private:
    Rewriter R;
};

int main(int argc, const char **argv)
{
    // Read all of standard input into a string
    std::string code(
        (std::istreambuf_iterator<char>(std::cin)),
        (std::istreambuf_iterator<char>())
    );

    // Build compiler arguments
    std::vector<std::string> args;

    // We must tell Clang this is C++ code, because memory buffers have no file extension
    args.push_back("-xc++");

    // Pass through any extra arguments from bash
    for (int i = 1; i < argc; ++i) {
        args.push_back(argv[i]);
    }

    // Run the tool directly on the string in memory
    bool success = runToolOnCodeWithArgs(
        std::make_unique<FixerAction>(),
        code,
        args
    );

    return success ? 0 : 1;
}
